### ISSUE TITLE
when i compile src code and run it， i got a exceptoin

### ISSUE THREAD

**Issue by TopSpoofer** [unicredit/hbase-rdd#20]
//my code
object MiniCluster {
  private val master = "local[4]"
  private val appName = "hbase-rdd_spark"

  def main(args: Array[String]) {
    implicit val config = HBaseConfig() // Assumes hbase-site.xml is on classpath

    val sparkConf = new SparkConf()
      .setMaster(master)
      .setAppName(appName)

    val sc = new SparkContext(sparkConf)
    sc.textFile("test-input")
      .map({ line =>
        val Array(k, col1, col2, _) = line split "\t"
        val content = Map("col1" -> col1, "col2" -> col2)

        k -> content
      }).toHBase("test-table", "cf1")
  }
}

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
	at org.apache.spark.util.Utils$.<init>(Utils.scala:1630)
	at org.apache.spark.util.Utils$.<clinit>(Utils.scala)
	at org.apache.spark.SparkConf.<init>(SparkConf.scala:59)
	at org.apache.spark.SparkConf.<init>(SparkConf.scala:53)
	at unicredit.spark.hbase.MiniCluster$.main(MiniCluster.scala:42)
	at unicredit.spark.hbase.MiniCluster.main(MiniCluster.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemUtils
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 11 more

**Comment by fralken** [comment]
Make sure that commons-lang3-3.3.2.jar is in your classpath

**Comment by TopSpoofer** [comment]
this lib not in sbt?

**Comment by TopSpoofer** [comment]
i add this lib to sbt, and compile it, but catch an exception：
 java.lang.ClassNotFoundException: unicredit.spark.hbase.MiniCluster$$anonfun$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)

the stack track is :

2016-03-15 11:10:18,999 WARN  [task-result-getter-1] scheduler.TaskSetManager (Logging.scala:logWarning(71)) - Lost task 1.0 in stage 0.0 (TID 1, 10.16.255.213): java.lang.ClassNotFoundException: unicredit.spark.hbase.MiniCluster$$anonfun$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:72)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:98)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

2016-03-15 11:10:19,009 INFO  [sparkDriver-akka.actor.default-dispatcher-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Starting task 1.1 in stage 0.0 (TID 2, 10.16.255.213, ANY, 2152 bytes)
2016-03-15 11:10:19,010 INFO  [task-result-getter-0] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 0.0 in stage 0.0 (TID 0) on executor 10.16.255.213: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 1]
2016-03-15 11:10:19,012 INFO  [sparkDriver-akka.actor.default-dispatcher-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Starting task 0.1 in stage 0.0 (TID 3, 10.16.255.211, ANY, 2152 bytes)
2016-03-15 11:10:19,098 INFO  [task-result-getter-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 1.1 in stage 0.0 (TID 2) on executor 10.16.255.213: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 2]
2016-03-15 11:10:19,099 INFO  [sparkDriver-akka.actor.default-dispatcher-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Starting task 1.2 in stage 0.0 (TID 4, 10.16.255.211, ANY, 2152 bytes)
2016-03-15 11:10:19,449 INFO  [sparkDriver-akka.actor.default-dispatcher-2] storage.BlockManagerInfo (Logging.scala:logInfo(59)) - Added broadcast_1_piece0 in memory on 10.16.255.211:46434 (size: 28.4 KB, free: 530.3 MB)
2016-03-15 11:10:19,722 INFO  [task-result-getter-3] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 0.1 in stage 0.0 (TID 3) on executor 10.16.255.211: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 3]
2016-03-15 11:10:19,728 INFO  [sparkDriver-akka.actor.default-dispatcher-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Starting task 0.2 in stage 0.0 (TID 5, 10.16.255.211, ANY, 2152 bytes)
2016-03-15 11:10:19,729 INFO  [task-result-getter-1] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 1.2 in stage 0.0 (TID 4) on executor 10.16.255.211: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 4]
2016-03-15 11:10:19,731 INFO  [sparkDriver-akka.actor.default-dispatcher-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Starting task 1.3 in stage 0.0 (TID 6, 10.16.255.212, ANY, 2152 bytes)
2016-03-15 11:10:19,833 INFO  [task-result-getter-0] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 0.2 in stage 0.0 (TID 5) on executor 10.16.255.211: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 5]
2016-03-15 11:10:19,835 INFO  [sparkDriver-akka.actor.default-dispatcher-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Starting task 0.3 in stage 0.0 (TID 7, 10.16.255.212, ANY, 2152 bytes)
2016-03-15 11:10:20,226 INFO  [sparkDriver-akka.actor.default-dispatcher-2] storage.BlockManagerInfo (Logging.scala:logInfo(59)) - Added broadcast_1_piece0 in memory on 10.16.255.212:50248 (size: 28.4 KB, free: 530.3 MB)
2016-03-15 11:10:20,485 INFO  [task-result-getter-2] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 1.3 in stage 0.0 (TID 6) on executor 10.16.255.212: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 6]
2016-03-15 11:10:20,487 ERROR [task-result-getter-2] scheduler.TaskSetManager (Logging.scala:logError(75)) - Task 1 in stage 0.0 failed 4 times; aborting job
2016-03-15 11:10:20,488 INFO  [task-result-getter-2] scheduler.TaskSchedulerImpl (Logging.scala:logInfo(59)) - Removed TaskSet 0.0, whose tasks have all completed, from pool 
2016-03-15 11:10:20,489 INFO  [task-result-getter-3] scheduler.TaskSetManager (Logging.scala:logInfo(59)) - Lost task 0.3 in stage 0.0 (TID 7) on executor 10.16.255.212: java.lang.ClassNotFoundException (unicredit.spark.hbase.MiniCluster$$anonfun$1) [duplicate 7]
2016-03-15 11:10:20,489 INFO  [task-result-getter-3] scheduler.TaskSchedulerImpl (Logging.scala:logInfo(59)) - Removed TaskSet 0.0, whose tasks have all completed, from pool 
2016-03-15 11:10:20,490 INFO  [dag-scheduler-event-loop] scheduler.TaskSchedulerImpl (Logging.scala:logInfo(59)) - Cancelling stage 0
2016-03-15 11:10:20,491 INFO  [dag-scheduler-event-loop] scheduler.DAGScheduler (Logging.scala:logInfo(59)) - ResultStage 0 (saveAsNewAPIHadoopDataset at HBaseWriteSupport.scala:90) failed in 4.181 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 6, 10.16.255.212): java.lang.ClassNotFoundException: unicredit.spark.hbase.MiniCluster$$anonfun$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)

**Comment by andreaferretti** [comment]
Can you please share:

* your `build.sbt` file, to see the dependencies, and
* the version of Spark you are running on?

The current version is designed to run on CDH 5.5.1. Previous versions were for previous versions of the CDH. If you are not running on the CDH, you may need to tweak your dependencies.

**Comment by TopSpoofer** [comment]
I never change the sbt content， and I sure the cdh version is 5.5.1， all of the components version match in sbt. I compile the src code in idea and run it in my machine that not in cdh cluster. The submission methods is Standalone.

**Comment by fralken** [comment]
All dependencies in sbt are `provided` which means that they must be provided at runtime in your classpath. Adding them in sbt is not the solution, but rather you should set up a cdh node (for example in a virtual machine) where an instance of hbase is running, and where all the required jars (hadoop, hbase, spark) are availble in the classpath.

**Comment by TopSpoofer** [comment]
i am run it at Intellij an i don't want to package it and use spark-sublimit to run the programe， how to make the required jars in the classpath？

**Comment by fralken** [comment]
It is not meant to be run directly from Intellij. What you can do is setup a local installation of Spark and HBase, and then run a spark-submit locally. Maybe you can create an Intellij run configuration so that you can start it directly from the ide.
Alternatively, you can develop some scalatest in a similar way of those in the project. Keep in mind that they work only with `sbt test` command line, and not from the ide (see #21)
