### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by xiaolezhu** [unicredit/hbase-rdd#23]
I am trying spark with hbase-rdd for bulk-loading and can't get ride of this permission denied issue, is there some setting I need to put on? I probably don't have permission to modify the hdfs-site.xml, and the setting there is:

  ```
 <property>
      <name>dfs.permissions.enabled</name>
      <value>true</value>
    </property>
    
    <property>
      <name>dfs.permissions.superusergroup</name>
      <value>hdfs</value>
    </property>

    <property>
      <name>fs.permissions.umask-mode</name>
      <value>022</value>
    </property>
```

 ```
User class threw exception: org.apache.hadoop.security.AccessControlException: Permission denied: user=tony, access=WRITE, inode="/user/yarn/hbase-staging/partitions_93adef32-3f25-49a0-a32c-c000f6bef025":yarn:hdfs:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:319)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:292)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:213)
at org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer$RangerAccessControlEnforcer.checkPermission(RangerHdfsAuthorizer.java:300)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:190)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1771)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1755)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1738)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInternal(FSNamesystem.java:2509)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2444)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2328)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:624)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:397)
at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2137)
at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2133)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2131)
``` 

During my experimental with Spark + hbase-rdd, I want to write 1 billion rows with 6 columns, what the performance expectation would be if there is any existing benchmark testing, I know it highly depends on hbase itself as well as data, just want to get some idea that how fast it would be?

Thanks in advance.

**Comment by vidma** [comment]
we've seen this after recent CDH upgrade (new HBase).

upgrading HBase dependency version might be the most right way to go (but for some, this might be pain in the ass with jar hell. screw you `jvm` :) ! )

there is a simpler temporary work-around, though - simply change your code to use this:
```diff
-  private implicit val hbaseConf: HBaseConfig = HBaseConfig()
+  private implicit val hbaseConf: HBaseConfig = HBaseConfig(
+    "hbase.fs.tmp.dir" -> "/user/YOUR-USER-YOU-RUN-SPARK-JOBS-WITH/hbase-staging"
+  )
```

why it works?
----

new HBase 1.2.0 constructs staging path somehow differently, based on `user.name` sys prop that is some magic  user the YARN job is run with (apparently `yarn`).

```java
// HConstants.java
/** Config key for hbase temporary directory in hdfs */
  public static final String TEMPORARY_FS_DIRECTORY_KEY = "hbase.fs.tmp.dir";
  public static final String DEFAULT_TEMPORARY_HDFS_DIRECTORY = "/user/"
      + System.getProperty("user.name") + "/hbase-staging";

// HFileOutputFormat2.java
String hbaseTmpFsDir = HConstants.TEMPORARY_FS_DIRECTORY_KEY or DEFAULT
          
```

**Comment by xiaolezhu** [comment]
Thanks @vidma. The work-around plays the trick! 👍 

I am using hbase-rdd by adding it as maven dependency, then construct the rdd like:

```
val bulk_load = urla_walk.map { x =>
        var sp = x.getAs[String]("name")
        val content = Map(
            cf -> Map("school" -> x.getAs[String]("school"),
                        "address" -> x.getAs[String]("address"),
                        "count" -> x.getAs[Long]("count")
                        ))
           (sp -> content)         
          }
```

and when I try to invoke bulk_load.toHBaseBulk(table, numFilesPerRegionPerFamily=32), there is an error:

> value toHBaseBulk is not a member of org.apache.spark.rdd.RDD[(String, scala.collection.immutable.Map[String,scala.collection.immutable.Map[String,Any]])]

So right now I convert the count to String and it works, from the wiki that I thought any type of the value would work : val rdd: RDD[(String, Map[String, A])], maybe I am still missing using it? would you please comment on it? :)

The only toHBaseBulk method that bulk_load can invoke is toHBaseBulk(table, numFilesPerRegionPerFamily=32), the same method with different parameter are not accessible like toHBaseBulk(tableNameStr: String, family: String, numFilesPerRegionPerFamily: Int = 1), I am guessing this is also because i miss-used this project in some way?

I am testing it by write 1 billion rows into HBase, probably not a good idea to store data in such a way :)

```
                <dependency>
			<groupId>eu.unicredit</groupId>
			<artifactId>hbase-rdd_2.10</artifactId>
			<version>0.7.1</version>
		</dependency>
```

**Comment by fralken** [comment]
Thanks @vidma  for sharing this workaround. I'm still on hbase 1.0.0 and haven't tested 1.2.0 yet.

@xiaolezhu when you have different types in your map's values (String and Long in your case), you get a Map[String, Any]. For this to work you must provide an instance of `Writes[Any]`, See #22 for a discussion on this.

Your solution to convert everything to String is correct, but maybe it is not what you want. An alternative is to explicitly convert everything to `Array[Byte]` (which would happen anyway before writing), and you can do this by calling the writers already defined as implicit for basic types (see `DefaultWrites.scala`). But again implementing a `Writes[Any]` that does this for you would probably be a better approach. 

As for the methods you can invoke for bulk load (as well for writing), they are 3:
- when you work with a single column family, and a fixed set of columns, you can use the following code, so that you move less data around spark tasks
```
 val rdd: RDD[(String, Seq[A])] = ...
 rdd.toHBaseBulk(table, cf, headers) 
```
- when you work with a single column family, but with a variable map of column/values (I mean records can have different sets of columns) you can use
```
val rdd: RDD[(String, Map[String, A])] = ...
rdd.toHBaseBulk(table, cf)
```
- finally, in the most generic case (many column families) you use (but this should be the last option)
```
val rdd: RDD[(String, Map[String, Map[String, A]])] = ...
rdd.toHBaseBulk(table)
```

In your case (1 column family and 6 columns) the first option would probably be the most efficient.

**Comment by xiaolezhu** [comment]
Thanks @fralken for such detailed explanations! :)
I had tried to use Bytes.toBytes() to write the value into hbase and will try implementing a Writes[Any].
