### ISSUE TITLE
java.lang.NullPointerException when reading non-existing column in version 0.5.0

### ISSUE THREAD

**Issue by kgrech** [unicredit/hbase-rdd#9]
I am trying to read the data from HBase using
`sc.hbase[String](hBaseTable, columns, filter)` method.
However my `columns` data stucture contatins a few columns which are not present in HBase. The defult behavior in version 0.4 was to ignore them.

In version 0.5.0 I am geeting the following error:

```
    java.lang.NullPointerException
	at org.apache.hadoop.hbase.CellUtil.cloneValue(CellUtil.java:81)
	at unicredit.spark.hbase.HBaseSC.unicredit$spark$hbase$HBaseSC$$read(HBaseReadSupport.scala:79)
	at unicredit.spark.hbase.HBaseSC$$anonfun$hbase$1$$anonfun$apply$2.apply(HBaseReadSupport.scala:134)
	at unicredit.spark.hbase.HBaseSC$$anonfun$hbase$1$$anonfun$apply$2.apply(HBaseReadSupport.scala:134)
	at unicredit.spark.hbase.HBaseSC$$anonfun$unicredit$spark$hbase$HBaseSC$$extract$1$$anonfun$1.apply(HBaseReadSupport.scala:62)
	at unicredit.spark.hbase.HBaseSC$$anonfun$unicredit$spark$hbase$HBaseSC$$extract$1$$anonfun$1.apply(HBaseReadSupport.scala:60)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:115)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:93)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at unicredit.spark.hbase.HBaseSC$$anonfun$unicredit$spark$hbase$HBaseSC$$extract$1.apply(HBaseReadSupport.scala:60)
	at unicredit.spark.hbase.HBaseSC$$anonfun$unicredit$spark$hbase$HBaseSC$$extract$1.apply(HBaseReadSupport.scala:58)
....
```

The reason for this issue is that in line number 61 `getColumnLatestCell` method returns null if the column is missing:
```scala
 val content = columns map { column =>
          val cell = result.getColumnLatestCell(cf.getBytes, column.getBytes)
          column -> read(cell)
        }  toMap
```

Before 0.5.0 we had a allCatch block there to hadle this issue:
```scala
 allCatch opt {
  CellUtil.cloneValue(cell)
 } map { value =>
  column -> reader.read(value)
}
```

Howerver in 0.5.0 we just have `colunm -> read(cell)` instead, where `read` method does not have exception handling:
```scala
 private def read[A](cell: Cell)(implicit reader: Reads[A]) = {
    val value = CellUtil.cloneValue(cell)
    reader.read(value)
  }
```

I think version 0.4 behavior was the most appropriate for the end user. Even if we want to track missing field, it should not be NullPointerException, which isn't informative.

**Comment by kgrech** [comment]
@andreaferretti  @fralken Please consider this fix. It is working fine for our environment. I think it would be good idea to realese 0.5.1 as a hot fix :)

**Comment by fralken** [comment]
My fault. During refactoring I missed the allCatch opt block. Thanks for pointing this out and for providing a fix.
